### ISSUE TITLE
is it possible to use HMR with the new angular-cli?

### ISSUE THREAD

**Issue by born2net** [AngularClass/angular-hmr#25]
is it possible to use HMR with the new angular-cli webpack?

regards,

Sean

**Comment by denkomanceski** [comment]
not yet :(

**Comment by born2net** [comment]
ok will wait patiently... tx

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean

**Comment by beeman** [comment]
Related: https://github.com/angular/angular-cli/pull/3330

**Comment by born2net** [comment]
thanks @beeman

**Comment by el-davo** [comment]
Theres a tutorial here - https://medium.com/@beeman/tutorial-enable-hmr-in-angular-cli-apps-1b0d13b80130
