### ISSUE TITLE
Angular 4.2.2: app component tag stacked instead of replacing the old one

### ISSUE THREAD

**Issue by almothafar** [AngularClass/angular-hmr#52]
I was trying to upgrade my Angular from 4.1.3 to 4.2.2, but got a critical issue that the component stacked instead of replacing it:

![image](https://user-images.githubusercontent.com/13887564/27065494-4250691a-5006-11e7-83e5-f2af67bd639e.png)

Downgrade solved issue, also, I tried to kill node.exe and run again the app, the issue was still occurring.

**Comment by Kamshak** [comment]
Having the same issue

**Comment by p3140** [comment]
+1 
May be related to [this one](https://github.com/aspnet/JavaScriptServices/issues/665) ?

**Comment by hrfarrokh** [comment]
me too

**Comment by jeandormehl** [comment]
Any news on this?

**Comment by Kamshak** [comment]
I have found a bit of a workaround for this by manually removing the element:

```ts
@NgModule({ ... })
class AppModule {
  constructor(public appRef: ApplicationRef) { }
  hmrOnDestroy() {
    const cmpLocation = this.appRef.components.map(cmp => cmp.location.nativeElement);
    // ...
    cmpLocation.forEach(elem => {
      (elem as any).remove();
    });
  }
}
```

**Comment by jeandormehl** [comment]
@Kamshak This method does indeed remove the additional app components appended onto the bottom of the page but all styling and input values are also lost for modals/popups.

**Comment by atomdmac** [comment]
+1

Saw this after re-building a docker image that was previously working fine.  I thought I was going crazy.  Downgrading "fixed" it.

**Comment by admosity** [comment]
Opened a PR based on what was said here, but haven't quite battle tested it. Using it now and it seems okay. @gdi2290 any idea what it might be?

**Comment by rafinskipg** [comment]
+1 hmr is useless for new releases of angular. And downgrading angular is not a solution ;)

**Comment by superstarmcawesome** [comment]
I'm still seeing this in 4.4.4 and 4.4.6.
