### ISSUE TITLE
updating 1.2.2 to version 2.1.1 is giving a could not find declaration file for module /@angularclass/hmr'

### ISSUE THREAD

**Issue by xtianus79** [AngularClass/angular-hmr#55]
Updating my dependencies I came across this error when updating from 1.2.2 to v 2.1.1 produces this error 

[at-loader] ./src/app/app.module.ts:7:69 
    TS7016: Could not find a declaration file for module '@angularclass/hmr'. '/xxx/xxx/xxx/node_modules/@angularclass/hmr/dist/index.js' implicitly has an 'any' type.

**Comment by DcsMarcRemolt** [comment]
The typings setting in package.json is missing. The typings are distributed correctly as it looks.

**Comment by jibbers42** [comment]
I have the same issue, the PR works for me.

**Comment by xtianus79** [comment]
Is anybody going to merge this and make this a new version?

**Comment by gdi2290** [comment]
merged as @angularclass/hmr@2.1.3
