### ISSUE TITLE
The <app> is not removed upon hmr run

### ISSUE THREAD

**Issue by rishabhmhjn** [AngularClass/angular-hmr#69]
I have been using `hmr` as per the configuration mentioned in [@AngularClass/angular-starter](https://github.com/AngularClass/angular-starter) example. I am facing an issue that when hmr runs, the old version of the root `<app>` component is not removed from the DOM.

Here is the screenshot of the elements. The first instance is the latest created element and the ones below are the old ones which are not being removed from the DOM.

![screenshot 2017-09-01 13 05 39](https://user-images.githubusercontent.com/1336602/29959727-4d1775d8-8f16-11e7-88b2-979de5d5a746.png)

Is there anything that I might be missing?
Thank you so much for this library and your support

**Comment by kubal5003** [comment]
I actually have the opposite problem - the old node is perfectly removed, new one is added, but nothing happens then - it's just an empty custom node and the application is not restarting and the whole tree of components is not regenerated..

**Comment by gdi2290** [comment]
The old problem should be solved in the latest version. For @kubal5003 do you have async routes?

**Comment by rishabhmhjn** [comment]
@gdi2290 the new version solved it. Thanks a tonne 👍 
Closing this one
